Core.cljs: removed start-drag - manually modifying the DOM is a bad idea and can cause these kinds of errors:
Error: Invariant Violation: findComponentRoot(..., .0.1.0.4.0.0.0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser). Try inspecting the child nodes of the element with React ID ``. react-0.9.0.js:15376

Manually modifying the DOM breaks React's diffing algorithm, use om/set-state! / om/transact! instead.